services:
  - type: web
    name: resumeiq-api
    env: python
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        value: jsearch.p.rapidapi.com
      - key: OPENAI_API_KEY
        sync: false
